#!/usr/bin/env node
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, readFile, writeFile, rm, symlink, copyFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { hash, filesUnder, IDENTITY_VERSION } from './shared.mjs';
import ts from 'typescript';
import { describeDiagnostic, semanticTokens, identityProducer } from './identity.mjs';
import { runCommand } from './unused.mjs';

const project = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const commandFile = path.join(project, 'scripts/quality-check.mjs');
const args = process.argv.slice(2);
if (args.length && (args.length !== 2 || args[0] !== '--output')) throw new Error('Usage: node scripts/quality/self-test.mjs [--output <new evidence directory>]');
const output = args.length ? path.resolve(args[1]) : await mkdtemp(path.join(os.tmpdir(), 'quality-self-test-evidence-'));
// Never overwrite an earlier failure or a prior run's evidence.
if (args.length) await mkdir(output, { recursive: false });
const fixture = await mkdtemp(path.join(os.tmpdir(), 'quality-self-test-project-'));
const cases = [];
let sequence = 0;
const initialProducerFiles = ['scripts/quality-check.mjs', ...await filesUnder(project, 'scripts/quality')];
const initialProducer = Object.fromEntries(await Promise.all(initialProducerFiles.map(async file => [file, hash(await readFile(path.join(project, file)))])));
const write = async (file, text) => { await mkdir(path.dirname(path.join(fixture, file)), { recursive: true }); await writeFile(path.join(fixture, file), text); };
const json = (file, value) => write(file, `${JSON.stringify(value, null, 2)}\n`);
async function reset() {
  for (const dir of ['src', 'tests', 'quality', 'contract-evidence']) await rm(path.join(fixture, dir), { recursive: true, force: true });
  await write('src/main.tsx', 'console.log("quality fixture");\n');
}
async function run(label, only, expected) {
  const directory = path.join(output, `${String(++sequence).padStart(2, '0')}-${label}`);
  await mkdir(directory);
  const source = {};
  for (const dir of ['src', 'tests', 'quality', 'contract-evidence']) {
    let files = [];
    try { files = await filesUnder(fixture, dir); } catch (error) { if (error.code !== 'ENOENT') throw error; }
    for (const file of files) source[file] = await readFile(path.join(fixture, file), 'utf8');
  }
  for (const file of ['package.json', 'tsconfig.app.json', 'tsconfig.json', 'eslint.config.mjs', 'knip.json']) source[file] = await readFile(path.join(fixture, file), 'utf8');
  const producerFiles = ['scripts/quality-check.mjs', ...await filesUnder(project, 'scripts/quality')];
  const producerSources = Object.fromEntries(await Promise.all(producerFiles.map(async file => [file, await readFile(path.join(project, file), 'utf8')])));
  const producerHashes = Object.fromEntries(Object.entries(producerSources).map(([file, text]) => [file, hash(text)]));
  assert.deepEqual(producerHashes, initialProducer, 'Quality producer changed during self-test; rerun on frozen code');
  await writeFile(path.join(directory, 'inputs.json'), JSON.stringify({ files: source, producerSources, producerHashes, hashes: Object.fromEntries(Object.entries(source).map(([file, text]) => [file, hash(text)])) }, null, 2));
  const command = await runCommand(process.execPath, [commandFile, '--root', fixture, ...(only ? ['--only', only] : []), '--report', path.join(directory, 'report.json')], project);
  await writeFile(path.join(directory, 'command.json'), JSON.stringify(command, null, 2));
  const report = JSON.parse(await readFile(path.join(directory, 'report.json'), 'utf8'));
  cases.push({ label, only: only ?? 'all', expected, actual: command.exitCode, directory: path.basename(directory), reportSHA256: hash(JSON.stringify(report)) });
  console.log(`${label}: exit ${command.exitCode} (expected ${expected})`);
  assert.equal(command.exitCode, expected, `${label}: ${command.stderr}\n${command.stdout}`);
  return report;
}
async function debtFor(report) {
  const grouped = new Map();
  for (const row of report.sections.lint.diagnostics.filter(row => row.severity === 2)) {
    assert.ok(row.signature, 'fixture diagnostic must be semantically anchored');
    const key = JSON.stringify([row.rule, row.file, row.signature]);
    const prior = grouped.get(key);
    if (prior) prior.count++;
    else grouped.set(key, { rule: row.rule, file: row.file, signature: row.signature, count: 1, reason: 'Synthetic reviewed object throw fixture only', owner: 'Quality gate self-test' });
  }
  const document = { schemaVersion: 1, identityVersion: IDENTITY_VERSION, identityProducer: await identityProducer(), allowances: [...grouped.values()] };
  await json('quality/debt.json', document);
  return document;
}
let failure;
try {
  await symlink(path.join(project, 'node_modules'), path.join(fixture, 'node_modules'), 'dir');
  await copyFile(path.join(project, 'eslint.config.mjs'), path.join(fixture, 'eslint.config.mjs'));
  await copyFile(path.join(project, 'tsconfig.app.json'), path.join(fixture, 'tsconfig.app.json'));
  await copyFile(path.join(project, 'knip.json'), path.join(fixture, 'knip.json'));
  await json('tsconfig.json', { extends: './tsconfig.app.json' });
  await json('package.json', { name: 'quality-fixture', private: true, type: 'module' });
  await reset();
  await run('clean-lint', 'lint', 0);
  await write('src/metric.ts', 'export function metric(a: boolean, b: boolean) { return a ? 1 : b ? 2 : 3; }\n');
  const metric = await run('review-warning-visible-nonblocking', 'lint', 0);
  const warning = metric.sections.lint.diagnostics.find(row => row.rule === 'no-nested-ternary');
  assert.ok(warning && warning.severity === 1 && warning.message && warning.line);
  assert.equal(metric.sections.lint.warningCounts['no-nested-ternary'], 1);
  const warningIdentity = describeDiagnostic('src/metric.ts', await readFile(path.join(fixture, 'src/metric.ts'), 'utf8'), { ...warning, ruleId: warning.rule });
  await json('quality/debt.json', { schemaVersion: 1, identityVersion: IDENTITY_VERSION, identityProducer: await identityProducer(), allowances: [{ rule: warning.rule, file: warning.file, signature: warningIdentity.signature, count: 1, reason: 'Synthetic warning allowance must be rejected as stale', owner: 'Quality gate self-test' }] });
  await run('warning-cannot-be-baselined', 'lint', 1);
  await reset();
  await write('src/unsafe.ts', 'export function unsafe(value: any) { return value.member; }\n');
  const unsafe = await run('typed-unsafe-fails', 'lint', 1);
  assert.ok(unsafe.sections.lint.diagnostics.some(row => row.rule.startsWith('@typescript-eslint/no-unsafe')));
  await rm(path.join(fixture, 'src/unsafe.ts'));
  await run('typed-unsafe-repair', 'lint', 0);
  await write('src/sonar.ts', 'export function choose(flag: boolean, other: boolean) { if (flag) { console.log("same"); } else if (other) { console.log("same"); } }\n');
  const sonar = await run('sonar-branches-fails', 'lint', 1);
  assert.ok(sonar.sections.lint.diagnostics.some(row => row.rule === 'sonarjs/no-duplicated-branches'));
  await write('src/sonar.ts', 'export function choose(flag: boolean) { console.log(flag ? "first" : "second"); }\n');
  await run('sonar-branches-repair', 'lint', 0);
  await reset();
  await write('src/hooks.tsx', 'import { useState } from "react";\nexport function Fixture({ active }: { active: boolean }) { if (active) useState(0); return null; }\n');
  const hooks = await run('real-hooks-fails', 'lint', 1);
  assert.ok(hooks.sections.lint.diagnostics.some(row => row.rule === 'react-hooks/rules-of-hooks'));
  await write('src/hooks.tsx', 'import { useState } from "react";\nexport function Fixture() { useState(0); return null; }\n');
  await run('real-hooks-repair', 'lint', 0);
  await reset();
  await write('src/throw.ts', 'export function fail(value: unknown) { throw value; }\n');
  const rawUnknown = await run('strict-raw-unknown-throw-fails', 'lint', 1);
  assert.ok(rawUnknown.sections.lint.diagnostics.some(row => row.rule === '@typescript-eslint/only-throw-error'));
  await write('src/throw.ts', 'export function fail(value: any) { throw value; }\n');
  const rawAny = await run('strict-raw-any-throw-fails', 'lint', 1);
  assert.ok(rawAny.sections.lint.diagnostics.some(row => row.rule === '@typescript-eslint/only-throw-error'));
  await write('src/throw.ts', 'export function fail() { const value = JSON.parse("null"); throw value; }\n');
  const newAny = await run('strict-new-any-throw-fails', 'lint', 1);
  assert.ok(newAny.sections.lint.diagnostics.some(row => row.rule === '@typescript-eslint/only-throw-error'));
  await write('src/throw.ts', 'export function fail() { try { JSON.parse("null"); } catch (error) { console.error(error); throw error; } }\n');
  const rethrow = await run('caught-rethrow-contract-pass', 'lint', 0);
  assert.ok(!rethrow.sections.lint.diagnostics.some(row => row.rule === '@typescript-eslint/only-throw-error'));
  await reset();
  const original = 'export function first(value: unknown) { throw { value }; }\n';
  await write('src/debt.ts', original);
  const debtReport = await run('unknown-throw-fails', 'lint', 1);
  assert.ok(debtReport.sections.lint.diagnostics.some(row => row.rule === '@typescript-eslint/only-throw-error'));
  const debt = await debtFor(debtReport);
  await run('reviewed-identity-pass', 'lint', 0);
  await write('src/debt.ts', '\n// relocation\nexport function first ( value : unknown ) {\n  throw { value } ;\n}\n');
  await run('format-and-line-relocation-pass', 'lint', 0);
  await write('src/debt.ts', original.replace('first', 'second'));
  await run('same-message-different-owner-fails', 'lint', 1);
  await write('src/debt.ts', 'export function first(value: unknown) { throw { value }; throw { value }; }\n');
  // Both duplicate nodes share the same semantic control-flow owner. A separate
  // unreachable-code finding is also correct; exact throw multiplicity must fail.
  const count = await run('identical-node-increase-fails', 'lint', 1);
  assert.ok(count.sections.lint.failures.some(row => row.kind === 'allowance-count-mismatch' && row.actual === row.expected + 1));
  await write('src/debt.ts', 'export function first(value: unknown, other: unknown) { console.log(value); throw { value: other }; }\n');
  await run('semantic-operand-mutation-fails', 'lint', 1);
  await write('src/debt.ts', original);
  await json('quality/debt.json', { ...debt, allowances: [...debt.allowances, debt.allowances[0]] });
  await run('duplicate-debt-key-fails', 'lint', 2);
  for (const field of ['reason', 'owner']) {
    await json('quality/debt.json', { ...debt, allowances: debt.allowances.map(row => ({ ...row, [field]: '' })) });
    await run(`invalid-debt-${field}-fails`, 'lint', 2);
  }
  await write('quality/debt.json', '{"schemaVersion":1,"schemaVersion":1,"identityVersion":"ts-ast-tokens-v1","allowances":[]}');
  await run('duplicate-json-property-fails', 'lint', 2);
  await json('quality/debt.json', { ...debt, allowances: debt.allowances.map(({ owner: _owner, ...row }) => row) });
  await run('missing-debt-owner-fails', 'lint', 2);
  await json('quality/debt.json', { ...debt, allowances: debt.allowances.map(row => ({ ...row, file: 'src/wrong.ts' })) });
  await run('wrong-debt-file-fails', 'lint', 1);
  await json('quality/debt.json', { ...debt, allowances: debt.allowances.map(row => ({ ...row, rule: 'unrelated/rule' })) });
  await run('wrong-debt-rule-fails', 'lint', 1);
  await json('quality/debt.json', { ...debt, identityProducer: { ...debt.identityProducer, sha256: '0'.repeat(64) } });
  await run('changed-identity-producer-fails', 'lint', 2);
  await json('quality/debt.json', { ...debt, allowances: debt.allowances.map(row => ({ ...row, count: 2 })) });
  await run('debt-count-decrease-fails', 'lint', 1);
  await json('quality/debt.json', debt);
  await write('src/debt.ts', 'export function first(value: unknown) { throw new Error(String(value)); }\n');
  await run('repaired-debt-stale-fails', 'lint', 1);
  await json('quality/debt.json', { ...debt, allowances: [] });
  await run('repaired-debt-shrunk-pass', 'lint', 0);
  await reset();
  const callbackBase = 'function invoke(label: string, callback: () => void) { console.log(label); callback(); }\n';
  const callbackFirst = callbackBase + 'export function flow(value: unknown) { invoke("first", () => { throw value; }); invoke("second", () => { console.log("safe"); }); }\n';
  await write('src/debt.ts', callbackFirst);
  const callbackReport = await run('anonymous-call-owner-unallowed-fails', 'lint', 1);
  await debtFor(callbackReport);
  await run('anonymous-call-owner-reviewed-pass', 'lint', 0);
  await write('src/debt.ts', callbackBase + 'export function flow(value: unknown) { invoke("first", () => { console.log("safe"); }); invoke("second", () => { throw value; }); }\n');
  await run('anonymous-sibling-debt-transfer-fails', 'lint', 1);
  await write('src/debt.ts', callbackBase + '\n// formatting and relocation\nexport function flow ( value : unknown ) { invoke ( "first" , () => { throw value ; } ) ; invoke("second", () => { console.log("safe"); }); }\n');
  await run('anonymous-call-owner-format-relocation-pass', 'lint', 0);
  await json('quality/debt.json', {schemaVersion: 1, identityVersion: IDENTITY_VERSION, identityProducer: await identityProducer(), allowances: []});
  await write('src/debt.ts', callbackBase + 'export function flow(value: unknown) { invoke("same", () => { throw value; }); invoke("same", () => { console.log("safe"); }); }\n');
  const ambiguous = await run('ambiguous-anonymous-owner-fails-unanchorable', 'lint', 1);
  assert.ok(ambiguous.sections.lint.failures.some(row => row.kind === 'unanchorable-diagnostic'));
  await reset();
  const parenthesizedBase = callbackBase + 'export function flow(value: unknown) { invoke("first", (() => { throw value; })); invoke("second", (() => { console.log("safe"); })); }\n';
  await write('src/debt.ts', parenthesizedBase);
  const parenthesized = await run('parenthesized-callback-unallowed-fails', 'lint', 1);
  await debtFor(parenthesized);
  await run('parenthesized-callback-reviewed-pass', 'lint', 0);
  await write('src/debt.ts', callbackBase + 'export function flow(value: unknown) { invoke("first", (() => { console.log("safe"); })); invoke("second", (() => { throw value; })); }\n');
  await run('parenthesized-callback-sibling-transfer-fails', 'lint', 1);
  await write('src/debt.ts', callbackFirst);
  await run('callback-parentheses-relocation-pass', 'lint', 0);
  await reset();
  const namedFirst = callbackBase + 'export function flow(value: unknown) { invoke("first", function callback() { throw value; }); invoke("second", function callback() { console.log("safe"); }); }\n';
  await write('src/debt.ts', namedFirst);
  const namedReport = await run('named-callback-unallowed-fails', 'lint', 1);
  await debtFor(namedReport);
  await run('named-callback-reviewed-pass', 'lint', 0);
  await write('src/debt.ts', callbackBase + 'export function flow(value: unknown) { invoke("first", function callback() { console.log("safe"); }); invoke("second", function callback() { throw value; }); }\n');
  await run('named-callback-sibling-transfer-fails', 'lint', 1);
  await write('src/debt.ts', callbackBase + '// relocation\nexport function flow (value : unknown) { invoke ("first", (function callback () { throw value ; })); invoke("second", function callback() { console.log("safe"); }); }\n');
  await run('named-callback-format-wrapper-relocation-pass', 'lint', 0);
  await json('quality/debt.json', {schemaVersion: 1, identityVersion: IDENTITY_VERSION, identityProducer: await identityProducer(), allowances: []});
  await write('src/debt.ts', callbackBase + 'export function flow(value: unknown) { invoke("same", function callback() { throw value; }); invoke("same", function callback() { console.log("safe"); }); }\n');
  const ambiguousNamed = await run('ambiguous-named-callback-unanchorable-fails', 'lint', 1);
  assert.ok(ambiguousNamed.sections.lint.failures.some(row => row.kind === 'unanchorable-diagnostic'));
  await reset();
  const namedRecursive = callbackBase + 'export function flow(value: unknown) { invoke("first", function callback() { if (Date.now() < 0) callback(); throw value; }); }\n';
  await write('src/debt.ts', namedRecursive);
  const recursiveReport = await run('named-recursive-callback-unallowed-fails', 'lint', 1);
  await debtFor(recursiveReport);
  await run('named-recursive-callback-reviewed-pass', 'lint', 0);
  await write('src/debt.ts', namedRecursive.replace('function callback()', 'function renamed()').replace('callback(); throw', 'renamed(); throw'));
  await run('named-callback-self-binding-change-fails', 'lint', 1);
  await reset();
  const dualBase = 'declare const invoke: { (label: string, callback: () => void): void; new (label: string, callback: () => void): object };\n';
  await write('src/debt.ts', dualBase + 'export function flow(value: unknown) { invoke("first", () => { throw value; }); }\n');
  const dualCall = await run('dual-call-callback-unallowed-fails', 'lint', 1);
  await debtFor(dualCall);
  await run('dual-call-callback-reviewed-pass', 'lint', 0);
  await write('src/debt.ts', dualBase + 'export function flow(value: unknown) { new invoke("first", () => { throw value; }); }\n');
  await run('call-to-constructor-debt-transfer-fails', 'lint', 1);
  await reset();
  const branchFirst = 'export function flow(value: unknown, first: boolean, second: boolean) { if (first) { throw value; } if (second) { console.log("safe"); } }\n';
  await write('src/debt.ts', branchFirst);
  const branch = await run('guarded-branch-unallowed-fails', 'lint', 1);
  await debtFor(branch);
  await run('guarded-branch-reviewed-pass', 'lint', 0);
  await write('src/debt.ts', 'export function flow(value: unknown, first: boolean, second: boolean) { if (first) { console.log("safe"); } if (second) { throw value; } }\n');
  await run('conditional-guard-debt-transfer-fails', 'lint', 1);
  await write('src/debt.ts', 'export function flow(value: unknown, first: boolean) { if (first) { throw value; } if (first) { console.log("safe"); } }\n');
  await json('quality/debt.json', {schemaVersion: 1, identityVersion: IDENTITY_VERSION, identityProducer: await identityProducer(), allowances: []});
  const guards = await run('ambiguous-repeated-guard-unanchorable-fails', 'lint', 1);
  assert.ok(guards.sections.lint.failures.some(row => row.kind === 'unanchorable-diagnostic'));
  await reset();
  // Regex and template tokens must retain parser context and distinguish mutation.
  await write('src/debt.ts', 'export function first(value: unknown) { throw /a[b/]c/.test(`x${String(value)}y`) ? { value } : { other: value }; }\n');
  const contextual = await run('contextual-tokens-unallowed-fails', 'lint', 1);
  await debtFor(contextual);
  await run('contextual-tokens-allowance-pass', 'lint', 0);
  const contextualIdentity = contextual.sections.lint.diagnostics.find(row => row.rule === '@typescript-eslint/only-throw-error');
  assert.ok(contextualIdentity.nodeTokens.some(([kind]) => kind === 'RegularExpressionLiteral'));
  assert.ok(contextualIdentity.nodeTokens.some(([kind]) => kind === 'TemplateHead'));
  const parsedContext = ts.createSourceFile('src/context.ts', 'const value = /a[b/]c/.test(`x${String(1)}y`);', ts.ScriptTarget.Latest, true);
  const parsedFormat = ts.createSourceFile('src/context.ts', 'const value = /a[b/]c/ . test ( `x${String(1)}y` ) ;', ts.ScriptTarget.Latest, true);
  assert.deepEqual(semanticTokens(parsedContext, parsedContext), semanticTokens(parsedFormat, parsedFormat), 'Parser-token API must ignore trivia while preserving regex/template context');
  await write('src/debt.ts', 'export function first(value: unknown) { throw /changed/.test(`x${String(value)}y`) ? { value } : { other: value }; }\n');
  await run('contextual-regex-mutation-fails', 'lint', 1);
  await reset();
  await write('src/domain/a.ts', 'import { db } from "../db/value"; export const value = db;\n');
  await write('src/db/value.ts', 'export const db = 1; export type Record = { id: string };\n');
  const boundary = await run('domain-db-value-boundary-fails', 'architecture', 1);
  assert.ok(boundary.sections.architecture.failures.some(row => row.kind === 'forbidden-value-edge'));
  await write('src/domain/a.ts', 'import { type Record } from "../db/value"; export { type Record as Alias } from "../db/value"; export type Other = Record;\n');
  await run('all-type-named-forms-pass', 'architecture', 0);
  await write('src/domain/a.ts', 'import { type Record, db } from "../db/value"; export const value: Record = { id: String(db) };\n');
  await run('mixed-type-value-boundary-fails', 'architecture', 1);
  await write('src/domain/a.ts', 'export { type Record, db } from "../db/value";\n');
  await run('mixed-reexport-value-boundary-fails', 'architecture', 1);
  await write('src/domain/a.ts', 'export type * from "../db/value";\n');
  await run('type-star-boundary-repair', 'architecture', 0);
  await write('src/db/value.ts', 'export { ui } from "../components/ui";\n');
  await write('src/components/ui.ts', 'export const ui = 1;\n');
  await run('db-ui-value-boundary-fails', 'architecture', 1);
  await write('src/db/value.ts', 'export const db = 1;\n');
  await write('src/domain/a.ts', 'export async function load() { return import("../db/value"); }\n');
  await run('literal-dynamic-boundary-fails', 'architecture', 1);
  await write('src/domain/a.ts', 'const value = require("../db/value"); export { value };\n');
  await run('literal-require-boundary-fails', 'architecture', 1);
  await reset();
  await write('src/a.ts', 'export { b } from "./b"; export const a = 1;\n');
  await write('src/b.ts', 'import { a } from "./a"; export const b = a;\n');
  const cycle = await run('static-value-cycle-fails', 'architecture', 1);
  assert.equal(cycle.sections.architecture.cycles.length, 1);
  await write('src/b.ts', 'export const b = 1;\n');
  await run('static-cycle-repair', 'architecture', 0);
  await write('src/a.ts', 'import type { B } from "./b"; export interface A { b?: B }\n');
  await write('src/b.ts', 'import { type A } from "./a"; export interface B { a?: A }\n');
  await run('type-only-cycle-allowed', 'architecture', 0);
  await write('src/a.ts', 'export { b } from "./b"; export const a = 1;\n');
  await write('src/b.ts', 'export async function b() { return import("./a"); }\n');
  const dynamic = await run('literal-dynamic-cycle-separated-pass', 'architecture', 0);
  assert.equal(dynamic.sections.architecture.dynamicValueEdges, 1);
  await write('src/b.ts', 'export async function b(name: string) { return import(name); }\n');
  const computed = await run('computed-import-limit-visible-pass', 'architecture', 0);
  assert.equal(computed.sections.architecture.computed.length, 1);
  await reset();
  const originalKnip = JSON.parse(await readFile(path.join(fixture, 'knip.json'), 'utf8'));
  await json('knip.json', {...originalKnip, treatConfigHintsAsErrors: true, ignoreDependencies: ['fixture-nonexistent-dependency']});
  await run('knip-config-hint-nonzero-with-empty-issues-fails', 'unused', 2);
  await write('src/config-orphan.ts', 'export const orphan = 1;\n');
  await run('knip-config-hint-nonzero-with-real-issues-fails', 'unused', 2);
  await rm(path.join(fixture, 'src/config-orphan.ts'));
  await json('knip.json', originalKnip);
  await run('clean-unused-pass', 'unused', 0);
  await write('src/orphan.ts', 'export const orphan = 1;\n');
  const orphan = await run('genuinely-unused-file-fails', 'unused', 1);
  assert.ok(orphan.sections.unused.candidates.some(row => row.issue === 'files' && row.file === 'src/orphan.ts'));
  await rm(path.join(fixture, 'src/orphan.ts'));
  await run('unused-file-removal-repair', 'unused', 0);
  await write('src/helper.ts', 'export const used = 1; export const unused = 2;\n');
  await write('src/main.tsx', 'import { used } from "./helper"; console.log(used);\n');
  const unused = await run('genuinely-unused-export-fails', 'unused', 1);
  assert.ok(unused.sections.unused.candidates.some(row => row.issue === 'exports' && row.symbol === 'unused'));
  const contract = { issue: 'exports', file: 'src/helper.ts', symbol: 'unused', count: 1, reason: 'Synthetic exact retained export to exercise contract enforcement', owner: 'Quality gate self-test', evidence: [{ file: 'src/helper.ts', sha256: hash(await readFile(path.join(fixture, 'src/helper.ts'))) }] };
  await json('quality/unused-contracts.json', { schemaVersion: 1, contracts: [contract] });
  await run('reviewed-unused-contract-pass', 'unused', 0);
  const evidenceFile = 'contract-evidence/retention.md';
  const evidenceText = 'Synthetic canonical contract: preserve the reviewed unused export.\n';
  await write(evidenceFile, evidenceText);
  const externalContract = { ...contract, evidence: [...contract.evidence, { file: evidenceFile, sha256: hash(evidenceText) }] };
  await json('quality/unused-contracts.json', { schemaVersion: 1, contracts: [externalContract] });
  const external = await run('external-contract-evidence-in-inventory-pass', 'unused', 0);
  assert.equal(external.inputs[evidenceFile], hash(evidenceText), 'Exact external contract evidence must participate in before/after inventory');
  await write(evidenceFile, `${evidenceText}Changed after the reviewed snapshot.\n`);
  await run('external-contract-evidence-hash-change-fails', 'unused', 2);
  await write(evidenceFile, evidenceText);
  await json('quality/unused-contracts.json', { schemaVersion: 1, contracts: [contract] });
  await json('quality/unused-contracts.json', { schemaVersion: 1, contracts: [contract, contract] });
  await run('duplicate-unused-key-fails', 'unused', 2);
  await json('quality/unused-contracts.json', { schemaVersion: 1, contracts: [{ ...contract, owner: '' }] });
  await run('invalid-unused-owner-fails', 'unused', 2);
  await json('quality/unused-contracts.json', { schemaVersion: 1, contracts: [{ ...contract, evidence: [] }] });
  await run('missing-unused-evidence-fails', 'unused', 2);
  await json('quality/unused-contracts.json', { schemaVersion: 1, contracts: [contract] });
  await write('src/new-orphan.ts', 'export const orphan = 1;\n');
  await run('added-unused-with-reviewed-contract-fails', 'unused', 1);
  await rm(path.join(fixture, 'src/new-orphan.ts'));
  await write('src/helper.ts', 'export const used = 1; export const unused = 3;\n');
  await run('unused-evidence-change-fails', 'unused', 2);
  await write('src/helper.ts', 'export const used = 1; export const unused = 2;\n');
  await write('src/main.tsx', 'import { used, unused } from "./helper"; console.log(used, unused);\n');
  await run('fixed-unused-contract-stale-fails', 'unused', 1);
  await json('quality/unused-contracts.json', { schemaVersion: 1, contracts: [] });
  await run('unused-export-consumer-repair', 'unused', 0);
  await write('src/main.tsx', 'import { used } from "./helper"; console.log(used);\n');
  await write('tests/helper.test.ts', 'import { unused } from "../src/helper"; console.log(unused); export const negativeTypeFixture = 1;\n');
  const testOnly = await run('full-test-consumer-retained-pass', 'unused', 0);
  assert.ok(testOnly.sections.unused.productionOnly.some(row => row.symbol === 'unused'));
  assert.ok(testOnly.sections.unused.outsideCandidateScope.some(row => row.symbol === 'negativeTypeFixture'));
  await run('complete-production-entry-pass', undefined, 0);
} catch (error) { failure = error.stack ?? String(error); console.error(failure); process.exitCode = 1; }
finally {
  const producerFiles = ['scripts/quality-check.mjs', ...await filesUnder(project, 'scripts/quality')];
  const producer = Object.fromEntries(await Promise.all(producerFiles.map(async file => [file, hash(await readFile(path.join(project, file)))])));
  await writeFile(path.join(output, 'summary.json'), `${JSON.stringify({ status: failure ? 'FAIL' : 'PASS', node: process.version, cases, failure, producer, initialProducer, producerUnchanged: JSON.stringify(producer) === JSON.stringify(initialProducer), limits: ['Bounded fixtures use the actual copied root ESLint/Knip configuration and installed dependency closure; this is not whole-product or Node22 clean-install proof.'] }, null, 2)}\n`);
  await rm(fixture, { recursive: true, force: true });
  console.log(`quality self-test: ${failure ? 'FAIL' : 'PASS'}; ${cases.length} cases; evidence ${output}`);
}
