import type { ChatModelMetadata } from "@/lib/ai/modelMetadata";
import type { AgentInteractionMode, AgentReasoningEffort } from "@/domain/agent";
import type { ReactNode } from "react";
import type { ConnectorConfig, Id, Project } from "@/domain/types";
import type { ChatModelPolicy } from "@/lib/ai/chatModelPolicy";

export type ChatSurfaceMode = "agent" | "task";
export type { AgentInteractionMode } from "@/domain/agent";

export type ComposerProps = {
  threadId?: string;
  value: string;
  sending: boolean;
  blocked?: boolean;
  blockedReason?: string;
  readOnly?: boolean;
  connectors: ConnectorConfig[];
  selectedConnectorId?: Id;
  model: string;
  reasoningEffort?: AgentReasoningEffort;
  onReasoningEffortChange: (value: AgentReasoningEffort | undefined) => void;
  modelMetadata?: Record<string, ChatModelMetadata>;
  modelOptions: Array<{ label: string; value: string }>;
  probingModels: boolean;
  modelPolicy: ChatModelPolicy;
  modelWarning?: string;
  chatMode: ChatSurfaceMode;
  projects: Project[];
  projectId?: Id;
  projectRequired?: boolean;
  projectLocked?: boolean;
  onProjectChange: (projectId: Id | undefined) => void | Promise<void>;
  interactionMode: AgentInteractionMode;
  onChange: (value: string) => void;
  onSend: () => void;
  onStop: () => void;
  onConnectorChange: (id: string) => void;
  onModelChange: (model: string) => void;
  onChatModeChange: (mode: ChatSurfaceMode) => void;
  onInteractionModeChange: (mode: AgentInteractionMode) => void;
  large?: boolean;
  contextUsage?: ReactNode;
  status?: ReactNode;
};
