/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioRouteImport } from './routes/_studio'
import { Route as StudioIndexRouteImport } from './routes/_studio.index'
import { Route as StudioCharactersRouteImport } from './routes/_studio.characters'
import { Route as StudioPropsRouteImport } from './routes/_studio.props'
import { Route as StudioScenesRouteImport } from './routes/_studio.scenes'
import { Route as StudioStylesRouteImport } from './routes/_studio.styles'
import { Route as PProjectIdRouteImport } from './routes/p.$projectId'
import { Route as PProjectIdIndexRouteImport } from './routes/p.$projectId.index'
import { Route as PProjectIdAssetsRouteImport } from './routes/p.$projectId.assets'
import { Route as PProjectIdPlanRouteImport } from './routes/p.$projectId.plan'
import { Route as PProjectIdProduceRouteImport } from './routes/p.$projectId.produce'
import { Route as PProjectIdReportRouteImport } from './routes/p.$projectId.report'
import { Route as PProjectIdShotsRouteImport } from './routes/p.$projectId.shots'
import { Route as PProjectIdStoryboardRouteImport } from './routes/p.$projectId.storyboard'
import { Route as PProjectIdWorldRouteImport } from './routes/p.$projectId.world'
import { Route as PProjectIdAssetsIndexRouteImport } from './routes/p.$projectId.assets.index'
import { Route as PProjectIdAssetsCharactersCharacterIdRouteImport } from './routes/p.$projectId.assets.characters.$characterId'
import { Route as PProjectIdAssetsScenesSceneIdRouteImport } from './routes/p.$projectId.assets.scenes.$sceneId'

const StudioRoute = StudioRouteImport.update({
  id: '/_studio',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const StudioCharactersRoute = StudioCharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => StudioRoute,
} as any)
const StudioPropsRoute = StudioPropsRouteImport.update({
  id: '/props',
  path: '/props',
  getParentRoute: () => StudioRoute,
} as any)
const StudioScenesRoute = StudioScenesRouteImport.update({
  id: '/scenes',
  path: '/scenes',
  getParentRoute: () => StudioRoute,
} as any)
const StudioStylesRoute = StudioStylesRouteImport.update({
  id: '/styles',
  path: '/styles',
  getParentRoute: () => StudioRoute,
} as any)
const PProjectIdRoute = PProjectIdRouteImport.update({
  id: '/p/$projectId',
  path: '/p/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectIdIndexRoute = PProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PProjectIdRoute,
} as any)
const PProjectIdAssetsRoute = PProjectIdAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => PProjectIdRoute,
} as any)
const PProjectIdPlanRoute = PProjectIdPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => PProjectIdRoute,
} as any)
const PProjectIdProduceRoute = PProjectIdProduceRouteImport.update({
  id: '/produce',
  path: '/produce',
  getParentRoute: () => PProjectIdRoute,
} as any)
const PProjectIdReportRoute = PProjectIdReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => PProjectIdRoute,
} as any)
const PProjectIdShotsRoute = PProjectIdShotsRouteImport.update({
  id: '/shots',
  path: '/shots',
  getParentRoute: () => PProjectIdRoute,
} as any)
const PProjectIdStoryboardRoute = PProjectIdStoryboardRouteImport.update({
  id: '/storyboard',
  path: '/storyboard',
  getParentRoute: () => PProjectIdRoute,
} as any)
const PProjectIdWorldRoute = PProjectIdWorldRouteImport.update({
  id: '/world',
  path: '/world',
  getParentRoute: () => PProjectIdRoute,
} as any)
const PProjectIdAssetsIndexRoute = PProjectIdAssetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PProjectIdAssetsRoute,
} as any)
const PProjectIdAssetsCharactersCharacterIdRoute =
  PProjectIdAssetsCharactersCharacterIdRouteImport.update({
    id: '/characters/$characterId',
    path: '/characters/$characterId',
    getParentRoute: () => PProjectIdAssetsRoute,
  } as any)
const PProjectIdAssetsScenesSceneIdRoute =
  PProjectIdAssetsScenesSceneIdRouteImport.update({
    id: '/scenes/$sceneId',
    path: '/scenes/$sceneId',
    getParentRoute: () => PProjectIdAssetsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof StudioIndexRoute
  '/characters': typeof StudioCharactersRoute
  '/props': typeof StudioPropsRoute
  '/scenes': typeof StudioScenesRoute
  '/styles': typeof StudioStylesRoute
  '/p/$projectId': typeof PProjectIdRouteWithChildren
  '/p/$projectId/assets': typeof PProjectIdAssetsRouteWithChildren
  '/p/$projectId/plan': typeof PProjectIdPlanRoute
  '/p/$projectId/produce': typeof PProjectIdProduceRoute
  '/p/$projectId/report': typeof PProjectIdReportRoute
  '/p/$projectId/shots': typeof PProjectIdShotsRoute
  '/p/$projectId/storyboard': typeof PProjectIdStoryboardRoute
  '/p/$projectId/world': typeof PProjectIdWorldRoute
  '/p/$projectId/': typeof PProjectIdIndexRoute
  '/p/$projectId/assets/': typeof PProjectIdAssetsIndexRoute
  '/p/$projectId/assets/characters/$characterId': typeof PProjectIdAssetsCharactersCharacterIdRoute
  '/p/$projectId/assets/scenes/$sceneId': typeof PProjectIdAssetsScenesSceneIdRoute
}
export interface FileRoutesByTo {
  '/characters': typeof StudioCharactersRoute
  '/props': typeof StudioPropsRoute
  '/scenes': typeof StudioScenesRoute
  '/styles': typeof StudioStylesRoute
  '/': typeof StudioIndexRoute
  '/p/$projectId/plan': typeof PProjectIdPlanRoute
  '/p/$projectId/produce': typeof PProjectIdProduceRoute
  '/p/$projectId/report': typeof PProjectIdReportRoute
  '/p/$projectId/shots': typeof PProjectIdShotsRoute
  '/p/$projectId/storyboard': typeof PProjectIdStoryboardRoute
  '/p/$projectId/world': typeof PProjectIdWorldRoute
  '/p/$projectId': typeof PProjectIdIndexRoute
  '/p/$projectId/assets': typeof PProjectIdAssetsIndexRoute
  '/p/$projectId/assets/characters/$characterId': typeof PProjectIdAssetsCharactersCharacterIdRoute
  '/p/$projectId/assets/scenes/$sceneId': typeof PProjectIdAssetsScenesSceneIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_studio': typeof StudioRouteWithChildren
  '/_studio/characters': typeof StudioCharactersRoute
  '/_studio/props': typeof StudioPropsRoute
  '/_studio/scenes': typeof StudioScenesRoute
  '/_studio/styles': typeof StudioStylesRoute
  '/p/$projectId': typeof PProjectIdRouteWithChildren
  '/_studio/': typeof StudioIndexRoute
  '/p/$projectId/assets': typeof PProjectIdAssetsRouteWithChildren
  '/p/$projectId/plan': typeof PProjectIdPlanRoute
  '/p/$projectId/produce': typeof PProjectIdProduceRoute
  '/p/$projectId/report': typeof PProjectIdReportRoute
  '/p/$projectId/shots': typeof PProjectIdShotsRoute
  '/p/$projectId/storyboard': typeof PProjectIdStoryboardRoute
  '/p/$projectId/world': typeof PProjectIdWorldRoute
  '/p/$projectId/': typeof PProjectIdIndexRoute
  '/p/$projectId/assets/': typeof PProjectIdAssetsIndexRoute
  '/p/$projectId/assets/characters/$characterId': typeof PProjectIdAssetsCharactersCharacterIdRoute
  '/p/$projectId/assets/scenes/$sceneId': typeof PProjectIdAssetsScenesSceneIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/characters'
    | '/props'
    | '/scenes'
    | '/styles'
    | '/p/$projectId'
    | '/p/$projectId/assets'
    | '/p/$projectId/plan'
    | '/p/$projectId/produce'
    | '/p/$projectId/report'
    | '/p/$projectId/shots'
    | '/p/$projectId/storyboard'
    | '/p/$projectId/world'
    | '/p/$projectId/'
    | '/p/$projectId/assets/'
    | '/p/$projectId/assets/characters/$characterId'
    | '/p/$projectId/assets/scenes/$sceneId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/characters'
    | '/props'
    | '/scenes'
    | '/styles'
    | '/'
    | '/p/$projectId/plan'
    | '/p/$projectId/produce'
    | '/p/$projectId/report'
    | '/p/$projectId/shots'
    | '/p/$projectId/storyboard'
    | '/p/$projectId/world'
    | '/p/$projectId'
    | '/p/$projectId/assets'
    | '/p/$projectId/assets/characters/$characterId'
    | '/p/$projectId/assets/scenes/$sceneId'
  id:
    | '__root__'
    | '/_studio'
    | '/_studio/characters'
    | '/_studio/props'
    | '/_studio/scenes'
    | '/_studio/styles'
    | '/p/$projectId'
    | '/_studio/'
    | '/p/$projectId/assets'
    | '/p/$projectId/plan'
    | '/p/$projectId/produce'
    | '/p/$projectId/report'
    | '/p/$projectId/shots'
    | '/p/$projectId/storyboard'
    | '/p/$projectId/world'
    | '/p/$projectId/'
    | '/p/$projectId/assets/'
    | '/p/$projectId/assets/characters/$characterId'
    | '/p/$projectId/assets/scenes/$sceneId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  StudioRoute: typeof StudioRouteWithChildren
  PProjectIdRoute: typeof PProjectIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_studio': {
      id: '/_studio'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_studio/': {
      id: '/_studio/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/characters': {
      id: '/_studio/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof StudioCharactersRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/props': {
      id: '/_studio/props'
      path: '/props'
      fullPath: '/props'
      preLoaderRoute: typeof StudioPropsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/scenes': {
      id: '/_studio/scenes'
      path: '/scenes'
      fullPath: '/scenes'
      preLoaderRoute: typeof StudioScenesRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/styles': {
      id: '/_studio/styles'
      path: '/styles'
      fullPath: '/styles'
      preLoaderRoute: typeof StudioStylesRouteImport
      parentRoute: typeof StudioRoute
    }
    '/p/$projectId': {
      id: '/p/$projectId'
      path: '/p/$projectId'
      fullPath: '/p/$projectId'
      preLoaderRoute: typeof PProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$projectId/': {
      id: '/p/$projectId/'
      path: '/'
      fullPath: '/p/$projectId/'
      preLoaderRoute: typeof PProjectIdIndexRouteImport
      parentRoute: typeof PProjectIdRoute
    }
    '/p/$projectId/assets': {
      id: '/p/$projectId/assets'
      path: '/assets'
      fullPath: '/p/$projectId/assets'
      preLoaderRoute: typeof PProjectIdAssetsRouteImport
      parentRoute: typeof PProjectIdRoute
    }
    '/p/$projectId/plan': {
      id: '/p/$projectId/plan'
      path: '/plan'
      fullPath: '/p/$projectId/plan'
      preLoaderRoute: typeof PProjectIdPlanRouteImport
      parentRoute: typeof PProjectIdRoute
    }
    '/p/$projectId/produce': {
      id: '/p/$projectId/produce'
      path: '/produce'
      fullPath: '/p/$projectId/produce'
      preLoaderRoute: typeof PProjectIdProduceRouteImport
      parentRoute: typeof PProjectIdRoute
    }
    '/p/$projectId/report': {
      id: '/p/$projectId/report'
      path: '/report'
      fullPath: '/p/$projectId/report'
      preLoaderRoute: typeof PProjectIdReportRouteImport
      parentRoute: typeof PProjectIdRoute
    }
    '/p/$projectId/shots': {
      id: '/p/$projectId/shots'
      path: '/shots'
      fullPath: '/p/$projectId/shots'
      preLoaderRoute: typeof PProjectIdShotsRouteImport
      parentRoute: typeof PProjectIdRoute
    }
    '/p/$projectId/storyboard': {
      id: '/p/$projectId/storyboard'
      path: '/storyboard'
      fullPath: '/p/$projectId/storyboard'
      preLoaderRoute: typeof PProjectIdStoryboardRouteImport
      parentRoute: typeof PProjectIdRoute
    }
    '/p/$projectId/world': {
      id: '/p/$projectId/world'
      path: '/world'
      fullPath: '/p/$projectId/world'
      preLoaderRoute: typeof PProjectIdWorldRouteImport
      parentRoute: typeof PProjectIdRoute
    }
    '/p/$projectId/assets/': {
      id: '/p/$projectId/assets/'
      path: '/'
      fullPath: '/p/$projectId/assets/'
      preLoaderRoute: typeof PProjectIdAssetsIndexRouteImport
      parentRoute: typeof PProjectIdAssetsRoute
    }
    '/p/$projectId/assets/characters/$characterId': {
      id: '/p/$projectId/assets/characters/$characterId'
      path: '/characters/$characterId'
      fullPath: '/p/$projectId/assets/characters/$characterId'
      preLoaderRoute: typeof PProjectIdAssetsCharactersCharacterIdRouteImport
      parentRoute: typeof PProjectIdAssetsRoute
    }
    '/p/$projectId/assets/scenes/$sceneId': {
      id: '/p/$projectId/assets/scenes/$sceneId'
      path: '/scenes/$sceneId'
      fullPath: '/p/$projectId/assets/scenes/$sceneId'
      preLoaderRoute: typeof PProjectIdAssetsScenesSceneIdRouteImport
      parentRoute: typeof PProjectIdAssetsRoute
    }
  }
}

interface StudioRouteChildren {
  StudioCharactersRoute: typeof StudioCharactersRoute
  StudioPropsRoute: typeof StudioPropsRoute
  StudioScenesRoute: typeof StudioScenesRoute
  StudioStylesRoute: typeof StudioStylesRoute
  StudioIndexRoute: typeof StudioIndexRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioCharactersRoute: StudioCharactersRoute,
  StudioPropsRoute: StudioPropsRoute,
  StudioScenesRoute: StudioScenesRoute,
  StudioStylesRoute: StudioStylesRoute,
  StudioIndexRoute: StudioIndexRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

interface PProjectIdAssetsRouteChildren {
  PProjectIdAssetsIndexRoute: typeof PProjectIdAssetsIndexRoute
  PProjectIdAssetsCharactersCharacterIdRoute: typeof PProjectIdAssetsCharactersCharacterIdRoute
  PProjectIdAssetsScenesSceneIdRoute: typeof PProjectIdAssetsScenesSceneIdRoute
}

const PProjectIdAssetsRouteChildren: PProjectIdAssetsRouteChildren = {
  PProjectIdAssetsIndexRoute: PProjectIdAssetsIndexRoute,
  PProjectIdAssetsCharactersCharacterIdRoute:
    PProjectIdAssetsCharactersCharacterIdRoute,
  PProjectIdAssetsScenesSceneIdRoute: PProjectIdAssetsScenesSceneIdRoute,
}

const PProjectIdAssetsRouteWithChildren =
  PProjectIdAssetsRoute._addFileChildren(PProjectIdAssetsRouteChildren)

interface PProjectIdRouteChildren {
  PProjectIdAssetsRoute: typeof PProjectIdAssetsRouteWithChildren
  PProjectIdPlanRoute: typeof PProjectIdPlanRoute
  PProjectIdProduceRoute: typeof PProjectIdProduceRoute
  PProjectIdReportRoute: typeof PProjectIdReportRoute
  PProjectIdShotsRoute: typeof PProjectIdShotsRoute
  PProjectIdStoryboardRoute: typeof PProjectIdStoryboardRoute
  PProjectIdWorldRoute: typeof PProjectIdWorldRoute
  PProjectIdIndexRoute: typeof PProjectIdIndexRoute
}

const PProjectIdRouteChildren: PProjectIdRouteChildren = {
  PProjectIdAssetsRoute: PProjectIdAssetsRouteWithChildren,
  PProjectIdPlanRoute: PProjectIdPlanRoute,
  PProjectIdProduceRoute: PProjectIdProduceRoute,
  PProjectIdReportRoute: PProjectIdReportRoute,
  PProjectIdShotsRoute: PProjectIdShotsRoute,
  PProjectIdStoryboardRoute: PProjectIdStoryboardRoute,
  PProjectIdWorldRoute: PProjectIdWorldRoute,
  PProjectIdIndexRoute: PProjectIdIndexRoute,
}

const PProjectIdRouteWithChildren = PProjectIdRoute._addFileChildren(
  PProjectIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  StudioRoute: StudioRouteWithChildren,
  PProjectIdRoute: PProjectIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
