/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PProjectIdRouteImport } from './routes/p.$projectId'
import { Route as PProjectIdIndexRouteImport } from './routes/p.$projectId.index'
import { Route as PProjectIdAssetsRouteImport } from './routes/p.$projectId.assets'
import { Route as PProjectIdPlanRouteImport } from './routes/p.$projectId.plan'
import { Route as PProjectIdReportRouteImport } from './routes/p.$projectId.report'
import { Route as PProjectIdStoryboardRouteImport } from './routes/p.$projectId.storyboard'
import { Route as PProjectIdAssetsIndexRouteImport } from './routes/p.$projectId.assets.index'
import { Route as PProjectIdAssetsCharactersCharacterIdRouteImport } from './routes/p.$projectId.assets.characters.$characterId'
import { Route as PProjectIdAssetsScenesSceneIdRouteImport } from './routes/p.$projectId.assets.scenes.$sceneId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectIdRoute = PProjectIdRouteImport.update({
  id: '/p/$projectId',
  path: '/p/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectIdIndexRoute = PProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PProjectIdRoute,
} as any)
const PProjectIdAssetsRoute = PProjectIdAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => PProjectIdRoute,
} as any)
const PProjectIdPlanRoute = PProjectIdPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => PProjectIdRoute,
} as any)
const PProjectIdReportRoute = PProjectIdReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => PProjectIdRoute,
} as any)
const PProjectIdStoryboardRoute = PProjectIdStoryboardRouteImport.update({
  id: '/storyboard',
  path: '/storyboard',
  getParentRoute: () => PProjectIdRoute,
} as any)
const PProjectIdAssetsIndexRoute = PProjectIdAssetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PProjectIdAssetsRoute,
} as any)
const PProjectIdAssetsCharactersCharacterIdRoute =
  PProjectIdAssetsCharactersCharacterIdRouteImport.update({
    id: '/characters/$characterId',
    path: '/characters/$characterId',
    getParentRoute: () => PProjectIdAssetsRoute,
  } as any)
const PProjectIdAssetsScenesSceneIdRoute =
  PProjectIdAssetsScenesSceneIdRouteImport.update({
    id: '/scenes/$sceneId',
    path: '/scenes/$sceneId',
    getParentRoute: () => PProjectIdAssetsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/p/$projectId': typeof PProjectIdRouteWithChildren
  '/p/$projectId/assets': typeof PProjectIdAssetsRouteWithChildren
  '/p/$projectId/plan': typeof PProjectIdPlanRoute
  '/p/$projectId/report': typeof PProjectIdReportRoute
  '/p/$projectId/storyboard': typeof PProjectIdStoryboardRoute
  '/p/$projectId/': typeof PProjectIdIndexRoute
  '/p/$projectId/assets/': typeof PProjectIdAssetsIndexRoute
  '/p/$projectId/assets/characters/$characterId': typeof PProjectIdAssetsCharactersCharacterIdRoute
  '/p/$projectId/assets/scenes/$sceneId': typeof PProjectIdAssetsScenesSceneIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/p/$projectId/plan': typeof PProjectIdPlanRoute
  '/p/$projectId/report': typeof PProjectIdReportRoute
  '/p/$projectId/storyboard': typeof PProjectIdStoryboardRoute
  '/p/$projectId': typeof PProjectIdIndexRoute
  '/p/$projectId/assets': typeof PProjectIdAssetsIndexRoute
  '/p/$projectId/assets/characters/$characterId': typeof PProjectIdAssetsCharactersCharacterIdRoute
  '/p/$projectId/assets/scenes/$sceneId': typeof PProjectIdAssetsScenesSceneIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/p/$projectId': typeof PProjectIdRouteWithChildren
  '/p/$projectId/assets': typeof PProjectIdAssetsRouteWithChildren
  '/p/$projectId/plan': typeof PProjectIdPlanRoute
  '/p/$projectId/report': typeof PProjectIdReportRoute
  '/p/$projectId/storyboard': typeof PProjectIdStoryboardRoute
  '/p/$projectId/': typeof PProjectIdIndexRoute
  '/p/$projectId/assets/': typeof PProjectIdAssetsIndexRoute
  '/p/$projectId/assets/characters/$characterId': typeof PProjectIdAssetsCharactersCharacterIdRoute
  '/p/$projectId/assets/scenes/$sceneId': typeof PProjectIdAssetsScenesSceneIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/p/$projectId'
    | '/p/$projectId/assets'
    | '/p/$projectId/plan'
    | '/p/$projectId/report'
    | '/p/$projectId/storyboard'
    | '/p/$projectId/'
    | '/p/$projectId/assets/'
    | '/p/$projectId/assets/characters/$characterId'
    | '/p/$projectId/assets/scenes/$sceneId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/p/$projectId/plan'
    | '/p/$projectId/report'
    | '/p/$projectId/storyboard'
    | '/p/$projectId'
    | '/p/$projectId/assets'
    | '/p/$projectId/assets/characters/$characterId'
    | '/p/$projectId/assets/scenes/$sceneId'
  id:
    | '__root__'
    | '/'
    | '/p/$projectId'
    | '/p/$projectId/assets'
    | '/p/$projectId/plan'
    | '/p/$projectId/report'
    | '/p/$projectId/storyboard'
    | '/p/$projectId/'
    | '/p/$projectId/assets/'
    | '/p/$projectId/assets/characters/$characterId'
    | '/p/$projectId/assets/scenes/$sceneId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PProjectIdRoute: typeof PProjectIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$projectId': {
      id: '/p/$projectId'
      path: '/p/$projectId'
      fullPath: '/p/$projectId'
      preLoaderRoute: typeof PProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$projectId/': {
      id: '/p/$projectId/'
      path: '/'
      fullPath: '/p/$projectId/'
      preLoaderRoute: typeof PProjectIdIndexRouteImport
      parentRoute: typeof PProjectIdRoute
    }
    '/p/$projectId/assets': {
      id: '/p/$projectId/assets'
      path: '/assets'
      fullPath: '/p/$projectId/assets'
      preLoaderRoute: typeof PProjectIdAssetsRouteImport
      parentRoute: typeof PProjectIdRoute
    }
    '/p/$projectId/plan': {
      id: '/p/$projectId/plan'
      path: '/plan'
      fullPath: '/p/$projectId/plan'
      preLoaderRoute: typeof PProjectIdPlanRouteImport
      parentRoute: typeof PProjectIdRoute
    }
    '/p/$projectId/report': {
      id: '/p/$projectId/report'
      path: '/report'
      fullPath: '/p/$projectId/report'
      preLoaderRoute: typeof PProjectIdReportRouteImport
      parentRoute: typeof PProjectIdRoute
    }
    '/p/$projectId/storyboard': {
      id: '/p/$projectId/storyboard'
      path: '/storyboard'
      fullPath: '/p/$projectId/storyboard'
      preLoaderRoute: typeof PProjectIdStoryboardRouteImport
      parentRoute: typeof PProjectIdRoute
    }
    '/p/$projectId/assets/': {
      id: '/p/$projectId/assets/'
      path: '/'
      fullPath: '/p/$projectId/assets/'
      preLoaderRoute: typeof PProjectIdAssetsIndexRouteImport
      parentRoute: typeof PProjectIdAssetsRoute
    }
    '/p/$projectId/assets/characters/$characterId': {
      id: '/p/$projectId/assets/characters/$characterId'
      path: '/characters/$characterId'
      fullPath: '/p/$projectId/assets/characters/$characterId'
      preLoaderRoute: typeof PProjectIdAssetsCharactersCharacterIdRouteImport
      parentRoute: typeof PProjectIdAssetsRoute
    }
    '/p/$projectId/assets/scenes/$sceneId': {
      id: '/p/$projectId/assets/scenes/$sceneId'
      path: '/scenes/$sceneId'
      fullPath: '/p/$projectId/assets/scenes/$sceneId'
      preLoaderRoute: typeof PProjectIdAssetsScenesSceneIdRouteImport
      parentRoute: typeof PProjectIdAssetsRoute
    }
  }
}

interface PProjectIdAssetsRouteChildren {
  PProjectIdAssetsIndexRoute: typeof PProjectIdAssetsIndexRoute
  PProjectIdAssetsCharactersCharacterIdRoute: typeof PProjectIdAssetsCharactersCharacterIdRoute
  PProjectIdAssetsScenesSceneIdRoute: typeof PProjectIdAssetsScenesSceneIdRoute
}

const PProjectIdAssetsRouteChildren: PProjectIdAssetsRouteChildren = {
  PProjectIdAssetsIndexRoute: PProjectIdAssetsIndexRoute,
  PProjectIdAssetsCharactersCharacterIdRoute:
    PProjectIdAssetsCharactersCharacterIdRoute,
  PProjectIdAssetsScenesSceneIdRoute: PProjectIdAssetsScenesSceneIdRoute,
}

const PProjectIdAssetsRouteWithChildren =
  PProjectIdAssetsRoute._addFileChildren(PProjectIdAssetsRouteChildren)

interface PProjectIdRouteChildren {
  PProjectIdAssetsRoute: typeof PProjectIdAssetsRouteWithChildren
  PProjectIdPlanRoute: typeof PProjectIdPlanRoute
  PProjectIdReportRoute: typeof PProjectIdReportRoute
  PProjectIdStoryboardRoute: typeof PProjectIdStoryboardRoute
  PProjectIdIndexRoute: typeof PProjectIdIndexRoute
}

const PProjectIdRouteChildren: PProjectIdRouteChildren = {
  PProjectIdAssetsRoute: PProjectIdAssetsRouteWithChildren,
  PProjectIdPlanRoute: PProjectIdPlanRoute,
  PProjectIdReportRoute: PProjectIdReportRoute,
  PProjectIdStoryboardRoute: PProjectIdStoryboardRoute,
  PProjectIdIndexRoute: PProjectIdIndexRoute,
}

const PProjectIdRouteWithChildren = PProjectIdRoute._addFileChildren(
  PProjectIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PProjectIdRoute: PProjectIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
